services:
  db:
    image: postgres:16
    container_name: petapp_postgres
    environment:
      POSTGRES_DB: petapp
      POSTGRES_USER: petapp_user
      POSTGRES_PASSWORD: petapp_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: